config/routes.rb
Association::Application.routes.draw do
  resources :agents

  root 'agents#index'

end

app/models/agent.rb
class Agent < ActiveRecord::Base
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_nil: true

  has_many :contacts, inverse_of: :agent
  accepts_nested_attributes_for :contacts, allow_destroy: true, reject_if: lambda {|attrs| attrs['phone'].blank? }
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :agent, inverse_of: :contacts
  validates :agent, presence: true

  # another strategy is validates :default, uniqueness: true with the agent scope
  # which requires previous default contact to be unmark first
  before_save :unique_default_per_agent

  private

  def unique_default_per_agent
    self.agent.contacts.update_all(default: false)
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  respond_to :html, :json

  before_action :set_agent, only: [:show, :edit, :update, :destroy]

  def index
    @agents = Agent.all
  end

  def show
  end

  def new
    @agent = Agent.new
  end

  def edit
  end

  def create
    @agent = Agent.new(agent_params)
    flash[:notice] = 'Agent was successfully created.' if @agent.save
    respond_with(@agent)
  end

  def update
    flash[:notice] = 'Agent was successfully updated.' if @agent.update(agent_params)
    respond_with(@agent)
  end

  def destroy
    @agent.destroy
    respond_with(@agent)
  end

  private

  def set_agent
    @agent = Agent.find(params[:id])
  end

  def agent_params
    params.require(:agent).permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agents/_form.html.erb
<%= form_for(@agent) do |f| %>
  <% if @agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agent.errors.count, "error") %> prohibited this agent from being saved:</h2>

      <ul>
      <% @agent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>

    <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </p>

    <h4>contacts</h4>

    <table>
      <tr>
        <th>id</th>
        <th>phone</th>
        <th>label</th>
        <th>default</th>
      </tr>
      <%= f.fields_for :contacts do |contact_form| %>
        <tr>
          <td><%= contact_form.object.id %></td>
          <td><%= contact_form.text_field :phone %></td>
          <td><%= contact_form.text_field :label %></td>
          <td><%= contact_form.select :default, options_for_select([true, false], contact_form.object.default) %></td>
        </tr>
      <% end %>

      <%= f.fields_for :contacts, f.object.contacts.build do |contact_form| %>
        <tr>
          <td>create a new contact</td>
          <td><%= contact_form.text_field :phone %></td>
          <td><%= contact_form.text_field :label %></td>
          <td><%= contact_form.select :default, options_for_select([true, false]) %></td>
        </tr>
      <% end %>
    </table>

    <%= f.submit %>
  </div>
<% end %>

app/views/agents/edit.html.erb
<h1>Editing agent</h1>

<%= render 'form' %>

<%= link_to 'Show', @agent %> |
<%= link_to 'Back', agents_path %>

app/views/agents/index.html.erb
<h1>Listing agents</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= agent.id %></td>
        <td><%= agent.name %></td>
        <td><%= link_to 'Show', agent %></td>
        <td><%= link_to 'Edit', edit_agent_path(agent) %></td>
        <td><%= link_to 'Destroy', agent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agent', new_agent_path %>

app/views/agents/new.html.erb
<h1>New agent</h1>

<%= render 'form' %>

<%= link_to 'Back', agents_path %>

app/views/agents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= label_tag :id %>
  <%= @agent.id %>
</p>

<p>
  <%= label_tag :name %>
  <%= @agent.name %>
</p>

<h4>contacts</h4>
<table>
  <tr>
    <th>id</th>
    <th>label</th>
    <th>phone</th>
    <th>default</th>
  </tr>
  <% @agent.contacts.each do |contact| %>
    <tr>
      <td><%= contact.id %></td>
      <td><%= contact.label %></td>
      <td><%= contact.phone %></td>
      <td><%= contact.default %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_agent_path(@agent) %> |
<%= link_to 'Back', agents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Association</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>